#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef LITESURVEY_SWIFT_H
#define LITESURVEY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import _LocationEssentials;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LiteSurvey",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

enum LiteSurveyDeviceType : NSInteger;
@class NSString;
SWIFT_CLASS("_TtC10LiteSurvey19AccessoryScanResult")
@interface AccessoryScanResult : NSObject
@property (nonatomic, readonly) enum LiteSurveyDeviceType type;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Work mode of the attitude sensor
typedef SWIFT_ENUM(NSInteger, AttitudeSensorMode, open) {
/// Sensor is powered down. When not in use, turn off the sensor to conserve battery.
  AttitudeSensorModeOff = 0,
/// This mode is used to calibrate the install angle of the attitude sensor. Calibration is always performed after assembly and before shipment.
  AttitudeSensorModeCalibration = 1,
/// Use this mode if the LiteSurvey device is used without a surveying pole.
  AttitudeSensorModeHandheld = 2,
/// Use this mode when LiteSurvey device is attached to a surveying pole.
  AttitudeSensorModeTilt = 3,
};

SWIFT_CLASS("_TtC10LiteSurvey20AttitudeSensorStatus")
@interface AttitudeSensorStatus : NSObject
@property (nonatomic, readonly) uint32_t rawValue;
@property (nonatomic, readonly) BOOL isReady;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// LiteSurvey device battery information
SWIFT_CLASS("_TtC10LiteSurvey16BatteryInfoModel")
@interface BatteryInfoModel : NSObject
/// Battery percentage remaining
@property (nonatomic, readonly) NSInteger percentageRemaining;
/// true if charger is connected, false otherwise
@property (nonatomic, readonly) BOOL chargerConnected;
/// true if battery is charging, false otherwise
@property (nonatomic, readonly) BOOL isCharging;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DataTransportType, open) {
  DataTransportTypeExternalAccessory = 0,
  DataTransportTypeBluetoothGATT = 1,
  DataTransportTypeBluetoothL2CAP = 2,
};

@protocol LiteSurveyDeviceDelegate;
@class LiteSurveyDeviceInfoModel;
enum NmeaType : NSInteger;
@class NtripAccountModel;
/// This interface provides access to LiteSurvey devices.
/// Methods contained in this interface allow applications to
/// <ol>
///   <li>
///     Scan for, connect to, and disconnect from LiteSurvey devices;
///   </li>
///   <li>
///     Change the settings of device’s output or peripherals;
///   </li>
///   <li>
///     Receive notifications when data have arrived from the device;
///   </li>
///   <li>
///     Query basic information about the device.
///   </li>
/// </ol>
SWIFT_CLASS("_TtC10LiteSurvey16LiteSurveyDevice")
@interface LiteSurveyDevice : NSObject
/// Delegate for monitoring data and connection status of LiteSurvey devices
@property (nonatomic, strong) id <LiteSurveyDeviceDelegate> _Nonnull delegate;
/// Initializes the LiteSurveyDevice with the provided delegate
- (nonnull instancetype)initWithDelegate:(id <LiteSurveyDeviceDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Use LiteSurveyDeviceScanner to scan. LiteSurveyDevice instance will be provided via delegate instead.", "LiteSurveyDeviceScanner.shared.startScan(delegate:)");
/// Attempts to disconnect from the LiteSurvey device. Monitor its progress with the deviceDidDisconnect callback
- (void)disconnect;
/// Display name of the LiteSurvey device
@property (nonatomic, readonly, copy) NSString * _Nullable displayName;
/// Scans for LiteSurvey devices (Bluetooth and USB serial).
/// If a LiteSurvey device is already discovered by the system when this function is called,
/// device connection will be automatically established. Otherwise, an Accessory Picker window will be shown.
/// After establishing a connection, the deviceDidConnect callback will be called.
- (void)startScan SWIFT_DEPRECATED_MSG("Use LiteSurveyDeviceScanner.shared.startScan instead.", "LiteSurveyDeviceScanner.shared.startScan(delegate:)");
/// Retrieves general information about the LiteSurvey device
///
/// returns:
/// General information about the LiteSurvey device
- (LiteSurveyDeviceInfoModel * _Nullable)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
/// Set the constellation systems used in position
/// \param enableGPS TRUE = enable GPS system, FALSE = disable GPS system
///
/// \param enableGLONASS TRUE = enable GLONASS system, FALSE = disable GLONASS system
///
/// \param enableGALILEO TRUE = enable GALILEO system, FALSE = disable GALILEO system
///
/// \param enableQZSS TRUE = enable QZSS system,FALSE = disable QZSS system
///
/// \param enableBeidou TRUE = enable Beidou system, FALSE = disable Beidou system
///
- (void)setGnssSystemsWithEnableGPS:(BOOL)enableGPS enableGLONASS:(BOOL)enableGLONASS enableGALILEO:(BOOL)enableGALILEO enableQZSS:(BOOL)enableQZSS enableBeidou:(BOOL)enableBeidou;
/// Sets the output rate of an NMEA message
/// \param nmeaType Type of an NMEA message
///
/// \param enable TRUE: enable FALSE:disable
///
- (void)setNmeaOutputWithNmeaType:(enum NmeaType)nmeaType enable:(BOOL)enable;
/// Enable the output of a RTCM message (if supported)
/// \param rtcmMessageNumbers RTCM message number
///
- (void)enableRtcmOutputWithRtcmMessageNumbers:(NSArray<NSNumber *> * _Nonnull)rtcmMessageNumbers;
/// Disable the output of a RTCM message (if supported)
- (void)disableRtcmOutput;
/// Enables or disables the laser of the LiteSurvey device
/// \param enable TRUE = enable laser. FALSE = disable laser.
///
- (void)setLaserStateWithEnable:(BOOL)enable;
- (void)setLaserRangingOutputRateWithRateMs:(NSInteger)rateMs;
/// Set the output rate of the inertial measurement unit (IMU), if available
/// \param rateMillis Output rate in milliseconds
///
- (void)setImuOutputWithRateMillis:(NSInteger)rateMillis;
/// Query whether firmware upgrade is available for this LiteSurvey device.
/// Monitor the didReceiveFirmwareUpgradeAvailability callback for results.
/// This request will send your basic device information (device ID, serial number, etc.) to Woncan servers.
- (void)queryFirmwareUpgrade;
/// Attempts to upgrade the firmware of this LiteSurvey device.
/// Monitor the firmwareUpgradeDidProgress callback for upgrade progress
/// This request will send your basic device information (device ID, serial number, etc.) to Woncan servers.
- (void)startFirmwareUpgrade;
/// Query NTRIP mountpoints for an NTRIP server
/// \param address IP address or URL of NTRIP server
///
/// \param port Port of NTRIP server
///
- (void)queryNtripMountpointWithAddress:(NSString * _Nonnull)address port:(NSInteger)port;
/// Configure the attitude sensor
/// \param mode See <code>AttitudeSensorMode</code>
///
/// \param poleHeight Pole height in meters. Only needed for <code>AttitudeSensorMode.Calibration</code> and <code>AttitudeSensorMode.Tilt</code>. Leave blank for other modes.
///
- (void)attitudeSensorConfigurationWithMode:(enum AttitudeSensorMode)mode poleHeight:(float)poleHeight;
/// Connect to the specified NTRIP account.
/// \param ntripAccount NTRIP account to connect
///
/// \param transmitNmeaPosition transmitNmeaPosition if true, location of LiteSurvey device will be transmitted to the NTRIP server.
///
- (void)startNtripConnectionWithNtripAccount:(NtripAccountModel * _Nonnull)ntripAccount transmitNmeaPosition:(BOOL)transmitNmeaPosition;
/// Disconnect NTRIP service for this LiteSurvey device
- (void)stopNtripConnection;
/// Retrieves details of currently active NTRIP account
- (NtripAccountModel * _Nullable)getNtripAccount SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10LiteSurvey10DemoDevice")
@interface DemoDevice : LiteSurveyDevice
@property (nonatomic, readonly, copy) NSString * _Nullable displayName;
- (void)followSystemLocation;
- (void)startRandomWalkWithInitialLocation:(CLLocationCoordinate2D)initialLocation;
- (void)connect;
- (nonnull instancetype)initWithDelegate:(id <LiteSurveyDeviceDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER;
- (void)startScan;
- (void)disconnect;
- (void)queryFirmwareUpgrade;
- (void)startFirmwareUpgrade;
- (void)startNtripConnectionWithNtripAccount:(NtripAccountModel * _Nonnull)ntripAccount transmitNmeaPosition:(BOOL)transmitNmeaPosition;
@end

@class CLLocationManager;
@class CLLocation;
@interface DemoDevice (SWIFT_EXTENSION(LiteSurvey)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
@end

/// Gnss fix status
/// status Integer representing the fix status as defined in NMEA GGA message
typedef SWIFT_ENUM_NAMED(NSInteger, GnssFixStatus, "GnssFixStatus", open) {
/// GNSS single solution, differential data not in use
  GnssFixStatusSingle = 1,
/// DGNSS solution, differential GNSS based on pseudorange only
  GnssFixStatusDGNSS = 2,
/// RTK fixed GNSS solution
  GnssFixStatusFixed = 4,
/// RTK float GNSS solution
  GnssFixStatusFloat = 5,
/// Simulated GNSS solution (used in demo mode only)
  GnssFixStatusSimulated = 8,
/// GNSS fix status invalid or unknown
  GnssFixStatusUnknown = 0,
};

typedef SWIFT_ENUM_NAMED(NSInteger, GnssSystem, "GnssSystem", open) {
  GnssSystemGPS = 0,
  GnssSystemGLONASS = 1,
  GnssSystemGALILEO = 2,
  GnssSystemQZSS = 3,
  GnssSystemBeidou = 4,
};

/// Inertial measurement unit (IMU) data
SWIFT_CLASS("_TtC10LiteSurvey12ImuInfoModel")
@interface ImuInfoModel : NSObject
/// Accelerometer X,Y,Z data in unit of gravitational acceleration g
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull accelerometer;
/// Gyroscope X,Y,Z in degrees per second
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull gyroscope;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface LiteSurveyDevice (SWIFT_EXTENSION(LiteSurvey))
- (void)setGnssSystems:(BOOL)enableGPS enableGLONASS:(BOOL)enableGLONASS enableGALILEO:(BOOL)enableGALILEO enableQZSS:(BOOL)enableQZSS enableBeidou:(BOOL)enableBeidou SWIFT_DEPRECATED_MSG("", "setGnssSystemsWithEnableGPS:enableGLONASS:enableGALILEO:enableQZSS:enableBeidou:");
- (void)setRtcmOutput:(NSArray * _Nonnull)rtcmMessageNumbers SWIFT_DEPRECATED_MSG("", "enableRtcmOutputWithRtcmMessageNumbers:");
- (void)setLaserState:(BOOL)enable SWIFT_DEPRECATED_MSG("", "setLaserStateWithEnable:");
- (void)setImuOutput:(int32_t)rateMillis SWIFT_DEPRECATED_MSG("", "setImuOutputWithRateMillis:");
- (void)queryNtripMountpoint:(NSString * _Nonnull)address port:(NSString * _Nonnull)port SWIFT_DEPRECATED_MSG("", "queryNtripMountpointWithAddress:port:");
- (void)startNtripConnection:(NtripAccountModel * _Nonnull)ntripAccount transmitNmeaPosition:(BOOL)transmitNmeaPosition SWIFT_DEPRECATED_MSG("", "startNtripConnectionWithNtripAccount:transmitNmeaPosition:");
- (void)setNmeaOutput:(enum NmeaType)nmeaType enable:(BOOL)enable SWIFT_DEPRECATED_MSG("", "setNmeaOutputWithNmeaType:enable:");
@end

@class LiteSurveyLocationModel;
@class SatelliteInfoModel;
@class NSData;
enum NtripConnectionStatus : NSInteger;
/// Delegate for monitoring data and connection status of LiteSurvey devices
SWIFT_PROTOCOL("_TtP10LiteSurvey24LiteSurveyDeviceDelegate_")
@protocol LiteSurveyDeviceDelegate
@optional
/// Called when a LiteSurvey device has connected.
/// \param device The connected LiteSurvey device
///
- (void)deviceDidConnectWithDevice:(LiteSurveyDevice * _Nonnull)device;
/// Called when a LiteSurvey device has disconnected.
/// \param device The connected LiteSurvey device
///
- (void)deviceDidDisconnectWithDevice:(LiteSurveyDevice * _Nonnull)device;
/// Called when general information about the device was received from a LiteSurvey device.
/// \param device The connected LiteSurvey device
///
/// \param deviceInfo General device information of the LiteSurvey device
///
- (void)didReceiveDeviceInfoWithDevice:(LiteSurveyDevice * _Nonnull)device deviceInfo:(LiteSurveyDeviceInfoModel * _Nonnull)deviceInfo;
/// Called when LiteSurvey device updates is location
/// \param location Location of the LiteSurvey device
///
- (void)didReceiveLocation:(LiteSurveyLocationModel * _Nonnull)location;
/// Called when LiteSurvey device updates satellite information
/// \param satelliteInfoList List of satellite information
///
- (void)didReceiveSatelliteInfo:(NSArray<SatelliteInfoModel *> * _Nonnull)satelliteInfoList;
/// Called when an NMEA message is received from LiteSurvey device
/// \param nmeaMessage NMEA message
///
- (void)didReceiveNmeaMessage:(NSString * _Nonnull)nmeaMessage;
/// Called when a RTCM message is received from LiteSurvey device
/// \param rtcmMessage RTCM message
///
- (void)didReceiveRtcmMessage:(NSData * _Nonnull)rtcmMessage;
/// Called when LiteSurvey device updates its battery information
/// \param batteryInfo Battery information of LiteSurvey device
///
- (void)didReceiveBatteryInfoWithDevice:(LiteSurveyDevice * _Nonnull)device batteryInfo:(BatteryInfoModel * _Nonnull)batteryInfo;
/// Called when the laser on LiteSurvey device was toggled
/// \param laserState true if laser was turned on, false if laser was turned off
///
- (void)laserStateDidChange:(BOOL)laserState;
/// Called when IMU data was received from LiteSurvey device
/// \param imuInfo IMU data
///
- (void)didReceiveImuData:(ImuInfoModel * _Nonnull)imuInfo;
/// Called when Woncan server reports whether a firmware upgrade for this LiteSurvey device is available
/// \param newFirmwareAvailable true if firmware upgrade is available, false otherwise
///
- (void)didReceiveFirmwareUpgradeAvailability:(BOOL)newFirmwareAvailable;
/// Called when firmware upgrade of LiteSurvey device has progressed
/// \param progressPercentage Progress percentage
///
- (void)firmwareUpgradeDidProgress:(NSInteger)progressPercentage;
/// Called when firmware update (query or the update itself) encounters an error
/// \param errorMessage Error message
///
- (void)firmwareUpgradeDidFailWithError:(NSString * _Nonnull)errorMessage;
/// called when ntrip mountpoint query failed
/// \param errorMessage error message
///
- (void)ntripMountpointQueryDidFailWithError:(NSString * _Nonnull)errorMessage;
/// Called when mountpoint list was retrieved from ntrip server
/// \param mountpointList List of ntrip mountpoints
///
- (void)ntripMountpointQueryDidFinishWithResult:(NSArray<NSString *> * _Nonnull)mountpointList;
/// Called when Ntrip connection status changes
/// \param ntripConnectionStatus Ntrip connection status
///
- (void)ntripConnectionStatusDidChange:(enum NtripConnectionStatus)ntripConnectionStatus;
/// Called when Ntrip connection fails
/// \param errorMessage Error message
///
- (void)ntripConnectionDidFailWithError:(NSString * _Nonnull)errorMessage;
- (void)scanDidFailWithErrorWithErrorMessage:(NSString * _Nonnull)errorMessage;
- (void)onAttitudeEulerAnglesWithStatus:(AttitudeSensorStatus * _Nonnull)status unixMs:(int64_t)unixMs roll:(float)roll pitch:(float)pitch yaw:(float)yaw varRoll:(float)varRoll varPitch:(float)varPitch varYaw:(float)varYaw varRollPitch:(float)varRollPitch varRollYaw:(float)varRollYaw varPitchYaw:(float)varPitchYaw;
- (void)onAttitudeSensorCalibrationResultWithAngles:(NSArray<NSNumber *> * _Nonnull)angles;
- (void)onAttitudeSensorCalibrationStatusWithTargetHeading:(NSInteger)targetHeading selectedHeadingZone:(NSInteger)selectedHeadingZone validPointCount:(NSArray<NSNumber *> * _Nonnull)validPointCount currentHeading:(NSInteger)currentHeading currentTilt:(NSInteger)currentTilt;
- (void)onTiltLocationChangedWithTiltLocation:(LiteSurveyLocationModel * _Nonnull)tiltLocation tiltDegrees:(float)tiltDegrees;
- (void)onLaserRangingResultWithDistanceMeters:(float)distanceMeters;
- (void)deviceDidDisconnect SWIFT_DEPRECATED_MSG("", "deviceDidDisconnectWithDevice:");
- (void)deviceDidConnect SWIFT_DEPRECATED_MSG("", "deviceDidConnectWithDevice:");
- (void)didReceiveBatteryInfo:(BatteryInfoModel * _Nonnull)batteryInfo SWIFT_DEPRECATED_MSG("", "didReceiveBatteryInfoWithDevice:batteryInfo:");
- (void)didReceiveDeviceInfo:(LiteSurveyDeviceInfoModel * _Nonnull)deviceInfo SWIFT_DEPRECATED_MSG("", "didReceiveDeviceInfoWithDevice:deviceInfo:");
@end

/// General information of a LiteSurvey device
SWIFT_CLASS("_TtC10LiteSurvey25LiteSurveyDeviceInfoModel")
@interface LiteSurveyDeviceInfoModel : NSObject
/// Device model
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceModel;
/// Device unique ID
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
/// Product name
@property (nonatomic, readonly, copy) NSString * _Nonnull productName;
/// Internal hardware identification number
@property (nonatomic, readonly, copy) NSString * _Nonnull serialNumber;
/// Firmware version
@property (nonatomic, readonly, copy) NSString * _Nonnull firmwareVersion;
/// Hardware version
@property (nonatomic, readonly, copy) NSString * _Nonnull hardwareVersion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10LiteSurvey25LiteSurveyDeviceInterface") SWIFT_DEPRECATED_MSG("", "_TtC10LiteSurvey16LiteSurveyDevice")
@interface LiteSurveyDeviceInterface : LiteSurveyDevice
- (nonnull instancetype)initWithDelegate:(id <LiteSurveyDeviceDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Use LiteSurveyDeviceScanner to scan. LiteSurveyDevice instance will be provided via delegate instead.", "LiteSurveyDeviceScanner.shared.startScan(delegate:)");
@end

SWIFT_CLASS("_TtC10LiteSurvey23LiteSurveyDeviceScanner")
@interface LiteSurveyDeviceScanner : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, LiteSurveyDeviceType, open) {
  LiteSurveyDeviceTypeGnssReceiver = 0,
  LiteSurveyDeviceTypeRadioReceiver = 1,
};

@class NSCoder;
@class NSDate;
@class CLLocationSourceInformation;
/// Location class as reported by LiteSurvey devices. Inherits from the system Location class.
SWIFT_CLASS("_TtC10LiteSurvey23LiteSurveyLocationModel")
@interface LiteSurveyLocationModel : CLLocation
/// GNSS fix status
@property (nonatomic, readonly) enum GnssFixStatus fixStatus;
/// Number of satellites in view
@property (nonatomic, readonly) NSInteger numSatsInView;
/// Number of satellites used in GNSS fix
@property (nonatomic, readonly) NSInteger numSatsInUse;
/// Differential reference station ID, 0000-1023
@property (nonatomic, readonly) NSInteger refStationId;
/// Age of Differential GNSS data in seconds
@property (nonatomic, readonly) float diffDataDelaySeconds;
/// Horizontal dilution of precision
@property (nonatomic, readonly) float hdop;
/// Vertical dilution of precision
@property (nonatomic, readonly) float vdop;
/// Position dilution of precision
@property (nonatomic, readonly) float pdop;
/// Geoidal Separation in meters
/// The difference between the WGS-84 earth ellipsoid surface and mean-sea-level (geoid) surface
@property (nonatomic, readonly) float geoidalSeparationMeters;
/// EllipsoidalAltitude
/// Returns the ellipsoidal altitude of the location under the WGS 84 reference frame.
/// Can be positive or negative.
@property (nonatomic, readonly) CLLocationDistance wgs84Altitude;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithLatitude:(CLLocationDegrees)latitude longitude:(CLLocationDegrees)longitude SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate altitude:(CLLocationDistance)altitude horizontalAccuracy:(CLLocationAccuracy)hAccuracy verticalAccuracy:(CLLocationAccuracy)vAccuracy timestamp:(NSDate * _Nonnull)timestamp SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate altitude:(CLLocationDistance)altitude horizontalAccuracy:(CLLocationAccuracy)hAccuracy verticalAccuracy:(CLLocationAccuracy)vAccuracy course:(CLLocationDirection)course speed:(CLLocationSpeed)speed timestamp:(NSDate * _Nonnull)timestamp SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate altitude:(CLLocationDistance)altitude horizontalAccuracy:(CLLocationAccuracy)hAccuracy verticalAccuracy:(CLLocationAccuracy)vAccuracy course:(CLLocationDirection)course courseAccuracy:(CLLocationDirectionAccuracy)courseAccuracy speed:(CLLocationSpeed)speed speedAccuracy:(CLLocationSpeedAccuracy)speedAccuracy timestamp:(NSDate * _Nonnull)timestamp SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate altitude:(CLLocationDistance)altitude horizontalAccuracy:(CLLocationAccuracy)hAccuracy verticalAccuracy:(CLLocationAccuracy)vAccuracy course:(CLLocationDirection)course courseAccuracy:(CLLocationDirectionAccuracy)courseAccuracy speed:(CLLocationSpeed)speed speedAccuracy:(CLLocationSpeedAccuracy)speedAccuracy timestamp:(NSDate * _Nonnull)timestamp sourceInfo:(CLLocationSourceInformation * _Nonnull)sourceInfo SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface LiteSurveyLocationModel (SWIFT_EXTENSION(LiteSurvey))
/// 用于倾斜测量，将倾斜测量的位置结果和原始位置model的解状态、DOP等信息融合，组成新的位置Model
- (nonnull instancetype)initWithLocation:(LiteSurveyLocationModel * _Nonnull)location latitude:(double)latitude longitude:(double)longitude altitude:(double)altitude hAcc:(double)hAcc vAcc:(double)vAcc;
@end

/// Types of NMEA messages
typedef SWIFT_ENUM_NAMED(NSInteger, NmeaType, "NmeaType", open) {
/// NMEA GGA message (Global Positioning System Fix Data)
  NmeaTypeGGA = 1,
/// NMEA GSA message (GNSS DOP and Active Satellites)
  NmeaTypeGSA = 2,
/// NMEA GSV message (GNSS Satellites In View)
  NmeaTypeGSV = 3,
/// NMEA RMC message (Recommended Minimum Specific GNSS Data)
  NmeaTypeRMC = 4,
/// NMEA VTG message (Course Over Ground & Ground Speed)
  NmeaTypeVTG = 5,
/// NMEA GST message (GNSS Pseudorange Error Statistics)
  NmeaTypeGST = 6,
/// NMEA ZDA message (Time & Date)
  NmeaTypeZDA = 7,
};

/// Ntrip account details
SWIFT_CLASS("_TtC10LiteSurvey17NtripAccountModel")
@interface NtripAccountModel : NSObject
/// IP address or URL
@property (nonatomic, copy) NSString * _Nonnull address;
/// Port number
@property (nonatomic) int32_t port;
/// mountpoint
@property (nonatomic, copy) NSString * _Nonnull mountpoint;
/// username
@property (nonatomic, copy) NSString * _Nonnull username;
/// password
@property (nonatomic, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithAddress:(NSString * _Nonnull)address port:(int32_t)port mountpoint:(NSString * _Nonnull)mountpoint username:(NSString * _Nonnull)username password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 测试Ntrip账户是否能登录
/// \param testDidSucceed 测试成功代理
///
/// \param testDidFail 测试失败代理（附带失败原因）
///
- (void)testAccountWithTestDidSucceed:(void (^ _Nullable)(void))testDidSucceed testDidFail:(void (^ _Nullable)(NSString * _Nonnull))testDidFail;
@end

/// Ntrip connection status
typedef SWIFT_ENUM_NAMED(NSInteger, NtripConnectionStatus, "NtripConnectionStatus", open) {
/// Ntrip connection  success
  NtripConnectionStatusSuccess = 0,
/// Ntrip connection  failed
  NtripConnectionStatusFailed = 1,
/// Ntrip connection  socket  closed
  NtripConnectionStatusSocketClosed = 2,
/// Connection was interrupted. Waiting for retry.
  NtripConnectionStatusRetrying = 3,
/// Attempting connection
  NtripConnectionStatusConnecting = 4,
};

@class SignalInfoModel;
/// GNSS Satellite information
SWIFT_CLASS("_TtC10LiteSurvey18SatelliteInfoModel")
@interface SatelliteInfoModel : NSObject
/// GNSS system / constellation of this satellite
@property (nonatomic, readonly) enum GnssSystem system;
/// FCN & OSN number for Glonass, PRN for other systems
@property (nonatomic, readonly) NSInteger satelliteId;
/// true if satellite was used in recent GNSS fix, false otherwise
@property (nonatomic, readonly) BOOL usedInFix;
/// elevation angle of this satellite, in degrees
@property (nonatomic, readonly) float elevationDegrees;
/// azimuth angle of this satellite, in degrees
@property (nonatomic, readonly) float azimuthDegrees;
/// List of signal information received by this satellite
@property (nonatomic, readonly, copy) NSArray<SignalInfoModel *> * _Nonnull signalList;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// GNSS Signal Information
SWIFT_CLASS("_TtC10LiteSurvey15SignalInfoModel")
@interface SignalInfoModel : NSObject
/// Signal Id number as defined by NMEA GSV message
@property (nonatomic, readonly) NSInteger gsvSignalId;
/// Name of the signal (for reference only)
@property (nonatomic, readonly, copy) NSString * _Nonnull signalName;
/// Signal-to-noise ratio (C/N0) in dBHz
@property (nonatomic, readonly) float cn0DbHz;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
